stats_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stats_tools.urls'))
]

stats_tools/urls.py
"""Define URL patterns for stats tools."""
from django.urls import path

from . import views

app_name = 'stats_tools'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('random_sample/', views.random_sample, name='random_sample'),
    path('upload_csv/', views.upload_csv, name='upload_csv')
]

stats_tools/models.py
from django.db import models


class RandomSample(models.Model):
    """Returns a set of random numbers to user"""
    min_value = models.IntegerField(max_length=100)
    max_value = models.IntegerField(max_length=100)
    rows = models.IntegerField(max_length=2000)
    columns = models.IntegerField(max_length=10)
    date_requested = models.DateTimeField(auto_now_add=True)
    export = models.BooleanField(default=False)

stats_tools/forms.py
from django import forms

from .models import RandomSample


class RandomSampleForm(forms.ModelForm):
    class Meta:
        model = RandomSample
        fields = ['min_value', 'max_value', 'rows', 'columns', 'export']
        labels = {'min_value': 'Minimum Value',
                  'max_value': 'Maximum Value',
                  'rows': 'Number of results to return:',
                  'columns': 'Number of columns to return',
                  'export': 'Export as CSV?'}

    def __init__(self, *args, **kwargs):
        super(RandomSampleForm, self).__init__(*args, **kwargs)

        # Set the default value for 'columns' field to 1
        self.fields['columns'].initial = 1


class UploadCsvForm(forms.Form):
    csv_file = forms.FileField()
    hist_options = forms.ChoiceField(choice=[('quantitative', 'Quantitative Histogram')], required=False)

stats_tools/views.py
import csv

from django.shortcuts import render
from django.http import HttpResponse
import pandas as pd
from django.template.context_processors import request

from .forms import RandomSampleForm, UploadCsvForm
from random_sample import RandomSample


def index(request):
    """Landing page for stats tools"""
    return render(request, 'stats_tools/index.html')


def random_sample(request):
    if request.method == 'POST':
        form = RandomSampleForm(request.POST)
        if form.is_valid():
            # retrieve input values from form
            min_value = form.cleaned_data['min_value']
            max_value = form.cleaned_data['max_value']
            rows = form.cleaned_data['rows']
            columns = form.cleaned_data['columns']
            export_csv = form.cleaned_data['export']

            # Create RandomSample object
            random_sample_instance = RandomSample(min_value, max_value)

            # Call the method to get results
            results = random_sample_instance.random_table(rows, columns, export_csv)

            if export_csv:
                # Return the CSV as a response
                response = HttpResponse(results, content_type='text/csv')
                response['Content-Disposition'] = 'attachment; filename=table.csv"'
                return response
            else:
                # Pass the results to the template
                return render(request, 'stats_tools/random_sample_results.html', {'results': results})

    else:
        # Display the form for GET requests
        form = RandomSampleForm()

    return render(request, 'stats_tools/random_sample.html', {'form': form})


def upload_csv(request):
    if request.method == 'POST':
        form = UploadCsvForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.files['csv_file']
            dataframe = pd.read_csv(csv_file)
    else:
        form = UploadCsvForm()

    return render(request, 'stats_tools/upload_csv.html', {'form': form})

stats_tools/templates/stats_tools/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>
    <a href="{% url 'stats_tools:index' %}">Home</a> -
    <a href="{% url 'stats_tools:random_sample' %}">Generate a Random Sample</a>
</p>
{% block content %}{% endblock content %}
</body>
</html>

stats_tools/templates/stats_tools/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stats Tools Home</title>
</head>
<body>
{% extends 'stats_tools/base.html' %}

{% block content %}
<h1>Stats Tools</h1>
<p>These are simple tools for learning statistics (and this site is a simple way for me to learn Django).</p>
{% endblock content %}
</body>
</html>

stats_tools/templates/stats_tools/random_sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Random Sample Generator</title>
</head>
<body>
{% extends 'stats_tools/base.html' %}
{% block content %}
<h1>Random Sample Form</h1>

    <h2>Random Sample Form</h2>
    <form action="{% url 'stats_tools:random_sample' %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}
</body>
</html>

stats_tools/templates/stats_tools/random_sample_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'stats_tools/base.html' %}

{% block content %}

<h1>Random Sample Form</h1>

<h2>Random Sample Results</h2>
<p>Here are your random numbers:</p>
{% if results %}<textarea>{% for result in results %}{{ result }}
{% endfor %}</textarea>
{% else %}
    <p>No results available.</p>
{% endif %}

{% endblock %}

</body>
</html>

stats_tools/templates/stats_tools/random_sample_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<h1>Random Sample Form</h1>

    <h2>Random Sample Form</h2>
    <form action="{% url 'stats_tools:random_sample_view' %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}
</body>
</html>

stats_tools/templates/stats_tools/upload_csv.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload CSV</title>
</head>
<body>
{% extends 'stats_tools/base.html' %}
{% block content %}
<h1>Random Sample Form</h1>

    <h2>Upload CSV</h2>
    <form action="{% url 'stats_tools:upload_csv' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <label for="id_histogram_options">Select Histogram Type: </label>
        {% form.histogram_options %}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}
</body>
</html>